name: Node.js CI

on:
  push:
    branches: [master]
    paths:
      - exercises/front-end/**
      - .github/workflows/front-end.yml
  pull_request:
    branches: [master]
    paths:
      - exercises/front-end/**
      - .github/workflows/front-end.yml

jobs:
  front-end:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: exercises/front-end

    strategy:
      matrix:
        node-version: [12, 14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
